//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwnd.DataAccess.Internal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_comment
    {
        public int Orders_commentID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> Confirmation_date { get; set; }
        public Nullable<int> Confirmation { get; set; }
        public string comment { get; set; }
    }
}
